name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - run: ls -R

      - run: chmod +x gradlew

      - run: ./gradlew bundleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./**/*.aab
